[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
evm_version = "paris"
via_ir = true
optimizer-runs = 100000

[fmt]
sort_imports = true
single_line_statement_blocks = "preserve"

[lint]
exclude_lints = [
    "screaming-snake-case-immutable",
    "mixed-case-function",
    "mixed-case-variable",
    "screaming-snake-case-const",
    "unwrapped-modifier-logic",
]
ignore = ["**/*.t.sol"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
