[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc-version = "0.8.24"
evm_version = "paris"
via_ir = true
optimizer-runs = 100000

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
